In [2]:
import pandas as pd
import glob

In [25]:
path = 'data/'

In [26]:
prod_files = glob.glob(f"{path}/*Produktionsplanung.xlsx")
prod_dfs = []

In [27]:
for file in prod_files:
    df = pd.read_excel(file)
    
    # leave only the necessary columns (the names are in German and in all files are the same)
    df_reduced = df[['Prod.Dat.', 'Gebinde', 'Bezeichnung']]
    
    # remame for convenience
    df_reduced.columns = ['date', 'gebinde', 'dish_name']
    
    # adding it to the dataframelist
    prod_dfs.append(df_reduced)

In [28]:
prod_full_df = pd.concat(prod_dfs, ignore_index=True)

In [29]:
prod_full_df.head(10)

        date            gebinde                      dish_name
0 2014-01-07               Reis                     Butterreis
1 2014-01-07         Kartoffeln           Kartoffeln, geschält
2 2014-01-07     Kartoffelsalat          Kartoffelsalat fertig
3 2014-01-07             Nudeln                 Nudeln Fusilli
4 2014-01-07            Spätzle                Spätzle, frisch
5 2014-01-07  Essen 1 Mensen VK           Hacklett - Hacksteak
6 2014-01-07  Essen 2 Mensen VK  Puten Cordon Bleu mit Zitrone
7 2014-01-07  Essen 3 Mensen VK    Pasta mit Tomate-Gemüsesoße
8 2014-01-07      Pommes frites                  Pommes-Frites
9 2014-01-08               Reis                     Butterreis

In [30]:
prod_full_df['date'] = pd.to_datetime(prod_full_df['date'], format='%d/%m/%Y')

In [31]:
prod_full_df.head(10)

        date            gebinde                      dish_name
0 2014-01-07               Reis                     Butterreis
1 2014-01-07         Kartoffeln           Kartoffeln, geschält
2 2014-01-07     Kartoffelsalat          Kartoffelsalat fertig
3 2014-01-07             Nudeln                 Nudeln Fusilli
4 2014-01-07            Spätzle                Spätzle, frisch
5 2014-01-07  Essen 1 Mensen VK           Hacklett - Hacksteak
6 2014-01-07  Essen 2 Mensen VK  Puten Cordon Bleu mit Zitrone
7 2014-01-07  Essen 3 Mensen VK    Pasta mit Tomate-Gemüsesoße
8 2014-01-07      Pommes frites                  Pommes-Frites
9 2014-01-08               Reis                     Butterreis

In [33]:
verkaufs_files = glob.glob(f"{path}/*Verkaufszahlen.xlsx")
verkaufs_dfs = []

In [41]:
df_raw = pd.read_excel('data/2014_Verkaufszahlen.xlsx', header=None)
dish_names = list(df_raw.loc[5:19, 6]) + list(df_raw.loc[21:30, 6])

In [42]:
dish_names

['Beilage Kartoffeln',
 'Gemüsereis',
 'Kartoffelkloss 200g',
 'Kartoffeln',
 'Kartoffelpüree',
 'Kartoffelsalat',
 'Kroketten',
 'Nudeln',
 'Pommes Wedges',
 'Pommes frites',
 'Reis',
 'Röstkartoffeln',
 'Semmelkloss',
 'Spätzle',
 'Tomatenreis',
 'Essen 1',
 'Essen 2',
 'Essen 3',
 'Essen 4',
 'Essen 5',
 'Essen BIO',
 'Essen Eichstätt',
 'Essen- Soziales ohne Berechnung',
 'Schöpfgericht 1,80€',
 'Wiener 1 Paar']

In [45]:
dates = list(df_raw.loc[3, 8:]) 
dates

['2014.01.07',
 nan,
 '2014.01.08',
 '2014.01.09',
 '2014.01.10',
 '2014.01.13',
 '2014.01.14',
 '2014.01.15',
 '2014.01.16',
 '2014.01.17',
 '2014.01.20',
 '2014.01.21',
 '2014.01.22',
 '2014.01.23',
 '2014.01.24',
 '2014.01.27',
 '2014.01.28',
 '2014.01.29',
 '2014.01.30',
 '2014.01.31',
 '2014.02.03',
 '2014.02.04',
 '2014.02.05',
 '2014.02.06',
 '2014.02.07',
 '2014.02.10',
 '2014.02.11',
 '2014.02.12',
 '2014.02.13',
 '2014.02.14',
 '2014.02.17',
 '2014.02.18',
 '2014.02.19',
 '2014.02.20',
 '2014.02.21',
 '2014.02.24',
 '2014.02.25',
 '2014.02.26',
 '2014.02.27',
 '2014.02.28',
 '2014.03.03',
 '2014.03.04',
 '2014.03.05',
 '2014.03.06',
 '2014.03.07',
 '2014.03.10',
 '2014.03.11',
 '2014.03.12',
 '2014.03.13',
 '2014.03.14',
 '2014.03.17',
 '2014.03.18',
 '2014.03.19',
 '2014.03.20',
 '2014.03.21',
 '2014.03.24',
 '2014.03.25',
 '2014.03.26',
 '2014.03.27',
 '2014.03.28',
 '2014.03.31',
 '2014.04.01',
 '2014.04.02',
 '2014.04.03',
 '2014.04.04',
 '2014.04.07',
 '2014.04.08',
 '2014.04.09',
 '2014.04.10',
 '2014.04.11',
 '2014.04.14',
 '2014.04.15',
 '2014.04.16',
 '2014.04.17',
 '2014.04.22',
 '2014.04.23',
 '2014.04.24',
 '2014.04.25',
 '2014.04.28',
 '2014.04.29',
 '2014.04.30',
 '2014.05.02',
 '2014.05.05',
 '2014.05.06',
 '2014.05.07',
 '2014.05.08',
 '2014.05.09',
 '2014.05.12',
 '2014.05.13',
 '2014.05.14',
 '2014.05.15',
 '2014.05.16',
 '2014.05.19',
 '2014.05.20',
 '2014.05.21',
 '2014.05.22',
 '2014.05.23',
 '2014.05.26',
 '2014.05.27',
 '2014.05.28',
 '2014.05.30',
 '2014.06.02',
 '2014.06.03',
 '2014.06.04',
 '2014.06.05',
 '2014.06.06',
 '2014.06.11',
 '2014.06.12',
 '2014.06.13',
 '2014.06.16',
 '2014.06.17',
 '2014.06.18',
 '2014.06.20',
 '2014.06.23',
 '2014.06.24',
 '2014.06.25',
 '2014.06.26',
 '2014.06.27',
 '2014.06.30',
 '2014.07.01',
 '2014.07.02',
 '2014.07.03',
 '2014.07.04',
 '2014.07.07',
 '2014.07.08',
 '2014.07.09',
 '2014.07.10',
 '2014.07.11',
 '2014.07.14',
 '2014.07.15',
 '2014.07.16',
 '2014.07.17',
 '2014.07.18',
 '2014.07.21',
 '2014.07.22',
 '2014.07.23',
 '2014.07.24',
 '2014.07.25',
 '2014.09.15',
 '2014.09.16',
 '2014.09.17',
 '2014.09.18',
 '2014.09.19',
 '2014.09.22',
 '2014.09.23',
 '2014.09.24',
 '2014.09.25',
 '2014.09.26',
 '2014.09.29',
 '2014.09.30',
 '2014.10.01',
 '2014.10.02',
 '2014.10.06',
 '2014.10.07',
 '2014.10.08',
 '2014.10.09',
 '2014.10.10',
 '2014.10.13',
 '2014.10.14',
 '2014.10.15',
 '2014.10.16',
 '2014.10.17',
 '2014.10.20',
 '2014.10.21',
 '2014.10.22',
 '2014.10.23',
 '2014.10.24',
 '2014.10.27',
 '2014.10.28',
 '2014.10.29',
 '2014.10.30',
 '2014.10.31',
 '2014.11.03',
 '2014.11.04',
 '2014.11.05',
 '2014.11.06',
 '2014.11.07',
 '2014.11.10',
 '2014.11.11',
 '2014.11.12',
 '2014.11.13',
 '2014.11.14',
 '2014.11.17',
 '2014.11.18',
 '2014.11.19',
 '2014.11.20',
 '2014.11.21',
 '2014.11.24',
 '2014.11.25',
 '2014.11.26',
 '2014.11.27',
 '2014.11.28',
 '2014.12.01',
 '2014.12.02',
 '2014.12.03',
 '2014.12.04',
 '2014.12.05',
 '2014.12.08',
 '2014.12.09',
 '2014.12.10',
 '2014.12.11',
 '2014.12.12',
 '2014.12.15',
 '2014.12.16',
 '2014.12.17',
 '2014.12.18',
 '2014.12.19',
 'Gesamt']