In [2]:
import pandas as pd
import glob

In [3]:
path = 'data/'
files = glob.glob(f"{path}/*Verkaufszahlen.xlsx")

In [8]:
df = pd.read_excel(files[0], header=2)

In [12]:
df

,Unnamed: 0,Ort,Unnamed: 2,Unnamed: 3,Artikel,Unnamed: 5,Gebinde,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 240,Unnamed: 241,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,year
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.01.09,NaN,...,2023.12.13,2023.12.14,2023.12.15,2023.12.18,2023.12.19,2023.12.20,2023.12.21,2023.12.22,Gesamt,2023
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
2,"Mensa KU, EI",NaN,NaN,NaN,VK Beilagen,NaN,Semmelkloss,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22,2023
3,NaN,NaN,NaN,NaN,NaN,NaN,Aufschlag Wechsel frittierte Beilagen,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37,2023
4,NaN,NaN,NaN,NaN,NaN,NaN,Beilage Fleisch/Wurst,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,270,2023
5,NaN,NaN,NaN,NaN,NaN,NaN,Kartoffelpüree,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,282,2023
6,NaN,NaN,NaN,NaN,NaN,NaN,Pommes Wedges,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288,2023
7,NaN,NaN,NaN,NaN,NaN,NaN,Nudeln,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308,2023
8,NaN,NaN,NaN,NaN,NaN,NaN,Röstkartoffeln,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,451,2023
9,NaN,NaN,NaN,NaN,NaN,NaN,Aufschlag Beilagenwechsel,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,908,2023
10,NaN,NaN,NaN,NaN,NaN,NaN,Spätzle,NaN,NaN,NaN,...,NaN,53,NaN,NaN,NaN,NaN,NaN,NaN,1324,2023
11,NaN,NaN,NaN,NaN,NaN,NaN,Reis,NaN,18,NaN,...,15,1,NaN,5,4,2,NaN,NaN,1539,2023
12,NaN,NaN,NaN,NaN,NaN,NaN,Kartoffelkloss 200g,NaN,NaN,NaN,...,NaN,146,NaN,NaN,NaN,NaN,NaN,NaN,1715,2023
13,NaN,NaN,NaN,NaN,NaN,NaN,Kartoffeln,NaN,NaN,NaN,...,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,2348,2023
14,NaN,NaN,NaN,NaN,NaN,NaN,Kartoffelsalat,NaN,74,NaN,...,NaN,39,6,13,NaN,NaN,4,NaN,2516,2023
15,NaN,NaN,NaN,NaN,NaN,NaN,Pommes frites,NaN,99,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,32,NaN,3969,2023
16,NaN,NaN,NaN,NaN,VK Beilagen Gesamt,NaN,NaN,NaN,192,NaN,...,15,239,10,18,4,2,36,NaN,15977,2023
17,NaN,NaN,NaN,NaN,VK Mensen Essen,NaN,Essen 7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19,2023
18,NaN,NaN,NaN,NaN,NaN,NaN,Essen Aktion 2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48,2023
19,NaN,NaN,NaN,NaN,NaN,NaN,Essen Eichstätt,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,753,2023
20,NaN,NaN,NaN,NaN,NaN,NaN,Essen Aktion 1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813,2023
21,NaN,NaN,NaN,NaN,NaN,NaN,Essen freier Preis,NaN,NaN,NaN,...,NaN,NaN,NaN,1,33,3,8,13,987,2023
22,NaN,NaN,NaN,NaN,NaN,NaN,Pizza Fleisch/Fisch,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1085,2023
23,NaN,NaN,NaN,NaN,NaN,NaN,Essen 3,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1800,2023
24,NaN,NaN,NaN,NaN,NaN,NaN,Pizza veget./vegan,NaN,19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3001,2023
25,NaN,NaN,NaN,NaN,NaN,NaN,Essen 2,NaN,175,NaN,...,NaN,139,NaN,NaN,NaN,NaN,NaN,NaN,12169,2023
26,NaN,NaN,NaN,NaN,NaN,NaN,Essen 5,NaN,NaN,NaN,...,176,NaN,91,201,252,106,NaN,NaN,16986,2023
27,NaN,NaN,NaN,NaN,NaN,NaN,Essen 4,NaN,219,NaN,...,279,250,151,208,89,325,167,NaN,28770,2023
28,NaN,NaN,NaN,NaN,NaN,NaN,Essen 1,NaN,93,NaN,...,149,175,150,70,164,69,115,NaN,29286,2023
29,NaN,NaN,NaN,NaN,VK Mensen Essen Gesamt,NaN,NaN,NaN,511,NaN,...,604,564,392,480,538,503,290,13,95717,2023
30,"Mensa KU, EI Gesamt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,703,NaN,...,619,803,402,498,542,505,326,13,111694,2023
31,Gesamt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,703,NaN,...,619,803,402,498,542,505,326,13,111694,2023

In [9]:
dfs = []
for file in files:
    df = pd.read_excel(file, header=2)  
    year = int(file.split('_')[0][-4:])  
    df['year'] = year
    dfs.append(df)

In [13]:
full_df = pd.concat(dfs, ignore_index=True)

In [14]:
full_df

,Unnamed: 0,Ort Nr.,Unnamed: 2,Unnamed: 3,Artikel,Unnamed: 5,Gebinde,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 240,Unnamed: 241,Unnamed: 242,Unnamed: 243,Unnamed: 244,Unnamed: 245,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.01.07,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,536,NaN,NaN,NaN,VK Beilagen,NaN,Beilage Kartoffeln,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,Gemüsereis,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,Kartoffelkloss 200g,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
283,NaN,NaN,NaN,NaN,NaN,NaN,Essen 4,NaN,219,NaN,...,279,250,151,208,89,325,167,NaN,28770,NaN
284,NaN,NaN,NaN,NaN,NaN,NaN,Essen 1,NaN,93,NaN,...,149,175,150,70,164,69,115,NaN,29286,NaN
285,NaN,NaN,NaN,NaN,VK Mensen Essen Gesamt,NaN,NaN,NaN,511,NaN,...,604,564,392,480,538,503,290,13,95717,NaN
286,"Mensa KU, EI Gesamt",NaN,NaN,NaN,NaN,NaN,NaN,NaN,703,NaN,...,619,803,402,498,542,505,326,13,111694,NaN
287,Gesamt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,703,NaN,...,619,803,402,498,542,505,326,13,111694,NaN